version: "2"

checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
plugins:
  fixme:
    enabled: false
  bundler-audit:
    enabled: true

exclude_patterns:
  - "*.*"
  - ".*"

  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile

  - assets/*
  - images/*
