title: Blog Ruby on Rails Indonesia
url: https://weblog.rails.id
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - HOWTO.md
  - Rakefile
permalink: "/:year/:i_month/:i_day/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
feed:
  path: feed/atom.xml
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/46654718
