plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - GUIDELINES.md
  - Rakefile
  - deploy_key
  - deploy_key.enc
  - deploy_key.pub
title: Blog Ruby on Rails Indonesia
description: Framework aplikasi web yang mencakup semua yang diperlukan untuk membuat aplikasi web yang didukung database sesuai dengan pola Model-View-Controller (MVC).
image: https://avatars.githubusercontent.com/u/46654718
url: https://weblog.rails.id
permalink: "/:year/:i_month/:i_day/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
feed:
  path: feed/atom.xml
lang: id_ID
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/46654718
ga_tracking_id: UA-133301636-2
